### ISSUE TITLE
AccessKey and SecretKey location

### ISSUE THREAD

**Issue by ajaysheoran2323** [godaddy/kubernetes-external-secrets#103]
Does anybody know where to put access_key and secret_access_key ?? I am getting below error:

```
{"level":50,"time":1561451711429,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","msg":"failure while polling the secrets","v":1}
{"level":50,"time":1561451711429,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","type":"Error","stack":"CredentialsError: Missing credentials in config\n at IncomingMessage.<anonymous> (/app/node_modules/aws-sdk/lib/util.js:865:34)\n at IncomingMessage.emit (events.js:194:15)\n at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n at endReadableNT (_stream_readable.js:1103:12)\n at process._tickCallback (internal/process/next_tick.js:63:19)","message":"Missing credentials in config","retryable":false,"time":"2019-06-25T08:35:11.429Z","code":"CredentialsError","originalError":{"message":"Could not load credentials from any providers","retryable":false,"time":"2019-06-25T08:35:11.429Z","code":"CredentialsError"},"msg":"Missing credentials in config","v":1}
{"level":30,"time":1561451721412,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","msg":"stopping and removing poller aws-s3-test-inside-k8s_242636","v":1}
{"level":30,"time":1561451721412,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","msg":"stopping poller","v":1}
{"level":30,"time":1561451721412,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","msg":"spinning up poller {\"id\":\"aws-s3-test-inside-k8s_242636\",\"namespace\":\"default\",\"secretDescriptors\":[{\"backendType\":\"secretsManager\",\"data\":[{\"key\":\"aws-s3-test-inside-k8s\",\"name\":\"aws-s3-test-inside-k8s\"}],\"name\":\"aws-s3-test-inside-k8s\"}],\"ownerReference\":{\"apiVersion\":\"kubernetes-client.io/v1\",\"controller\":true,\"kind\":\"ExternalSecret\",\"name\":\"aws-s3-test-inside-k8s\",\"uid\":\"cef0de83-9702-11e9-a5e5-42010a8000aa\"}}","v":1}
{"level":30,"time":1561451721412,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","msg":"starting poller","v":1}
{"level":30,"time":1561451731421,"pid":17,"hostname":"kubernetes-external-secrets-f99689c5d-kml69","msg":"running poll","v":1}
{"level":30,"
```

**Comment by jeffpearce** [comment]
Hi @ajaysheoran2323. It looks like it can't find your AWS credentials

**Comment by jeffpearce** [comment]
Hi @ajaysheoran2323. Can you set them via environment variables? Either locally or via helm?

**Comment by jeffpearce** [comment]
Hi @ajaysheoran2323. I wanted to follow up to see whether you are still having problems?

**Comment by red8888** [comment]
Im having this issue as well trying to run on gke, I am seeing this error in the logs:
"failure while polling the secrets {}"   
Im not seeing what the actual error is beyond that message

I confirmed these env vars are set in the pod and the creds have access to get my secrets:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

**Comment by red8888** [comment]
@ajaysheoran2323 this is actually working for me (i was using an outdated docker image)

set these env vars:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION
AWS_DEFAULT_REGION

I haven't confirmed but Im pretty sure you need to set AWS_DEFAULT_REGION to point the aws sm client to the region with your secrets. I added AWS_DEFAULT_REGION when troubleshooting with the wrong image and didnt remove it to confirm its necessary

**Comment by red8888** [comment]
confirmed AWS_DEFAULT_REGION is not necessary
