### ISSUE TITLE
Useless error message: cannot load secret marked for deletion

### ISSUE THREAD

**Issue by derrickburns** [godaddy/kubernetes-external-secrets#114]
You don't say WHICH secret! :)

```
 {"level":50,"time":1562830012963,"pid":17,"hostname":"dev-external-secrets-kubernetes-external-secrets-794fd9688z2x2n","type":"Error","stack":"InvalidRequest │
│ Exception: You can’t perform this operation on the secret because it was marked for deletion.\n    at Request.extractError (/app/node_modules/aws-sdk/lib/pro │
│ tocol/json.js:51:27)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws- │
│ sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/app/node_modules/aw │
│ s-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/s │
│ tate_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/ │
│ request.js:685:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)","message":"You can’t perform this operation o │
│ n the secret because it was marked for deletion.","code":"InvalidRequestException","time":"2019-07-11T07:26:52.963Z","requestId":"cf010d22-7f47-435f-9acb-19e │
│ 0044a384c","statusCode":400,"retryable":false,"retryDelay":31.423678272763624,"msg":"You can’t perform this operation on the secret because it was marked for │
│  deletion.","v":1}                                                                                                                                            │
│ {"level":30,"time":15
```

**Comment by Flydiverny** [comment]
Believe this was resolved with #146 and further improved with #194, please reopen if this is still an issue!
