### ISSUE TITLE
dataFrom not working properly

### ISSUE THREAD

**Issue by manuel-sanchez** [godaddy/kubernetes-external-secrets#246]
Hi, I really like the idea of the tool, and want to send a kudos to the team to start with. However, for some reason the dataFrom option is not working as expected. I tried with several layouts and none work. Here's the latest layout I have

```kind: ExternalSecret
metadata:
  name: ring-admin
secretDescriptor:
  backendType: systemManager
  dataFrom: /ring-admin/dev
```

This is the output I get from the external-secrets pod:

```{"level":30,"time":1576107445534,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","msg":"stopping poller for default/ring-admin","v":1}
{"level":30,"time":1576107445534,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","msg":"starting poller for default/ring-admin","v":1}
{"level":30,"time":1576107448254,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","msg":"stopping poller for default/ring-admin","v":1}
{"level":30,"time":1576107448262,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","msg":"starting poller for default/ring-admin","v":1}
{"level":30,"time":1576107455530,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","msg":"running poll on the secret default/ring-admin","v":1}
{"level":50,"time":1576107455539,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","msg":"failure while polling the secret default/ring-admin","stack":"TypeError: dataFrom.map is not a function\n    at SystemManagerBackend._fetchDataFromValues (/app/lib/backends/kv-backend.js:62:33)\n    at SystemManagerBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:100:12)\n    at Poller._createSecretManifest (/app/lib/poller.js:87:8)\n    at Poller._upsertKubernetesSecret (/app/lib/poller.js:150:39)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Poller._poll (/app/lib/poller.js:113:7)","type":"Error","v":1}
```

Any idea what can I be doing wrong? 
Thanks

**Comment by Flydiverny** [comment]
`dataFrom` should be an array :) 

See example here https://github.com/godaddy/kubernetes-external-secrets/blob/master/examples/data-from-example.yml

**Comment by manuel-sanchez** [comment]
Hi @Flydiverny yeah, I tried that too:

```apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ring-admin
spec:
  backendType: systemManager
  data: 
    - key: /ring-admin/dev/AIRBRAKE_PROJECT_KEY
      name: AIRBRAKE_PROJECT_KEY
  dataFrom:
    - /ring-admin/dev
```

If I leave the data part it works, if I add the dataFrom it doesn't error is:

```
{"level":50,"time":1576109103793,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-55dc7557d5-2lm5x","message":null,"code":"ParameterNotFound","time":"2019-12-12T00:05:03.792Z","requestId":"b09e12d6-28e9-41c5-839d-167c4997c1b4","statusCode":400,"retryable":false,"retryDelay":11.607949606815726,"msg":"failure while polling the secret default/ring-admin","stack":"ParameterNotFound: null\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)","type":"Error","v":1}
```

**Comment by Flydiverny** [comment]
Does the secret key `/ring-admin/dev` exist in system manager?
Or are you perhaps looking for another feature like the one suggested in this PR https://github.com/godaddy/kubernetes-external-secrets/pull/238?

**Comment by manuel-sanchez** [comment]
Maybe I'm confusing the features? The idea I had was to pull all key values from a given path and I thought this was the right feature. Let me know and I'll close this one

**Comment by Flydiverny** [comment]
`dataFrom` will pull a specific secret, which can be formatted as JSON.

Ie

In secret backend you have the secret `/ring-admin/dev`
Which has a value of 
```json
{
  "username": "hello",
  "password": "world"
}
``` 

Using this with `dataFrom`
```yaml
kind: ExternalSecret
metadata:
  name: ring-admin
spec:
  backendType: systemManager
  dataFrom:
    - /ring-admin/dev
```

Should give you a secret like 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ring-admin
data:
  username: <base64 of hello>
  password: <base64 of world>
type: Opaque
```


---

As opposed to using `data` to grab each property, to get the same results above:

```yaml
kind: ExternalSecret
metadata:
  name: ring-admin
spec:
  backendType: systemManager
  data:
    - key: /ring-admin/dev
      name: username
      property: username
    - key: /ring-admin/dev
      name: password
      property: password
```

**Comment by manuel-sanchez** [comment]
Ok, thanks @Flydiverny definitely the one I was thinking about was #238 thanks for the help. I'll see if there's anything I can contribute to that feature, closing this one
