### ISSUE TITLE
Want to know what types of Kubernetes secret type are supported?

### ISSUE THREAD

**Issue by sudarshntn** [godaddy/kubernetes-external-secrets#298]
Want to know what types of Kubernetes secret type are supported?
As I see only Opaque type is supported.

As I have the type: kubernetes.io/dockerconfigjson  which I use to store the Docker Image Pull credentials. But I have my Secret.yaml defined as 

# Docker Secrets
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: myregistrykey
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "demo.labels" .  | indent 4 }}
type: kubernetes.io/dockerconfigjson
spec:
  backendType: vault
  vaultMountPoint: demo-secret-sud4
  vaultRole: demo
  data:
    - name: .dockerconfigjson
      key: demo/demo-secret-sud4/devops-demo/myregistrykey/.dockerconfigjson

It creates as 

apiVersion: v1
data:
  .dockerconfigjson: ++++++++
kind: Secret
metadata:
  name: myregistrykey
  ownerReferences:
    - apiVersion: kubernetes-client.io/v1
      controller: true
      kind: ExternalSecret
      name: myregistrykey
type: Opaque

How do I have different types used in the Kubernetes-External-Secret CRD.

**Comment by sudarshntn** [comment]
When I use the template with type in the External-secret.yaml for docker credential pull secret  
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: myregistrykey
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "demo.labels" .  | indent 4 }}
spec:
  backendType: vault
  template:
    type: kubernetes.io/dockerconfigjson
  vaultMountPoint: demo-secret-sud4
  vaultRole: demo
  data:
    - name: .dockerconfigjson
      key: demo/demo-secret-sud4/devops-demo/myregistrykey/.dockerconfigjson

I get the below error : 

{"level":50,"time":1584246508766,"pid":17,"hostname":"external-secrets-kubernetes-external-secrets-7f8dd6f547-t8lq8","code":422,"statusCode":422,"msg":"failure while polling the secret dev-core/myregistrykey","stack":"Error: Secret \"myregistrykey\" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": json: cannot unmarshal string into Go value of type map[string]interface {}\n    at /app/node_modules/kubernetes-client/backends/request/client.js:231:25\n    at Request._callback (/app/node_modules/kubernetes-client/backends/request/client.js:168:14)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.EventEmitter.emit (domain.js:476:20)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:210:5)\n    at Request.EventEmitter.emit (domain.js:476:20)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:299:28)","type":"Error","v":1}

**Comment by sudarshntn** [comment]
The issue is in the vault the value should be proper JSON format else will face this error. Once I fix it works fine.
