### ISSUE TITLE
Unable to fetch data from Vault using the Kubernetes Auth Method

### ISSUE THREAD

**Issue by sudarshntn** [godaddy/kubernetes-external-secrets#400]
Unable to fetch data from Vault using the Kubernetes Auth Method

Have Hashi corp vault with TLS enabled and with Certificates.
Vault version : 1.4.0
Kubernetes Cluster version : 1.15.12

After adding the same certificates with External Secret Engine deployment see this error 

```js
{
  "level": 50,
  "time": 1591340479493,
  "pid": 17,
  "hostname": "external-secrets-kubernetes-external-secrets-698db9fd79-9qmzv",
  "response": {
    "statusCode": 400,
    "body": {
      "errors": [
        "missing client token"
      ]
    }
  },
  "stack": "Error: missing client token
    at handleVaultResponse (/app/node_modules/node-vault/src/index.js:49:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async VaultBackend._get (/app/lib/backends/vault-backend.js:42:21)
    at async /app/lib/backends/kv-backend.js:29:31
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async VaultBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:116:42)
    at async Poller._createSecretManifest (/app/lib/poller.js:88:18)
    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:152:28)",
  "type": "Error",
  "msg": "failure while polling the secret loadbalancer/ingress-tls"
}
```

**Comment by omerlh** [comment]
Had the same issue, solved it by setting `vaultMountPoint: kubernetes`

**Comment by pkrishnath** [comment]
Yes `vaultMountPoint: kubernetes` does the trick

**Comment by Flydiverny** [comment]
@sudarshntn please reopen if the above doesn't solve your error.
