### ISSUE TITLE
not having ssl verify disable functionality to get secret data from vault backend

### ISSUE THREAD

**Issue by tonythomasm** [godaddy/kubernetes-external-secrets#427]
I am trying to use external-secrets with vault-backend in openshift cluster. Using Kubernetes Auth Method to authenticate wityh vault. But the cluster certificate is self signed, because of that getting below error while getting secret property value from vault using KES:

```json
{"level":50,"time":1594281490196,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-5747ccf748-dvp2w","name":"RequestError","message":"Error: self signed certificate in certificate chain","cause":{"code":"SELF_SIGNED_CERT_IN_CHAIN"},"error":{"code":"SELF_SIGNED_CERT_IN_CHAIN"},"options":{"json":{"role":"app-role","jwt":"eyJhbGciOiJSUzI1NiIsImtpZCI6IkJyd19ubU9BeWdYRU1WUDdyTEUyQU1WNWpPeV9CRUZpT1F4ZHRoRWxJYXMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3bHQtdG9rZW5yZXZpZXctdG9rZW4tdmx2NHMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidmF1bHQtdG9rZW5yZXZpZXciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkYmMzMWNhOC02NTg4LTRlOWMtOGZkMy00M2MwY2FlMWNiZWUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YXJnb2NkOnZhdWx0LXRva2VucmV2aWV3In0.qML69mLzDBGL-KuR-jfZzVq4_l45EDevHPD6y_9_95McF8RZ23ZDoLcBq3izoAEI__aSr3Q2hvWPWi953gL9lAS5ZDXMmHaZgLux3nz09grjjdDjiCWnkZp83hEG2oTaxjZloYH4i4LO7Ym90NZccKGjIPSr9HFZnbjNDgzevMha-8YkaT3VJoBB_prBs46VIlrlJX9jwzqE-RuO7vaiiUslNErkbaEeN35MzfXpWx_4u9P0gxXPqZtP9tUAIaFJ1QbpiCvLCXqHLTmzq6OV-z2q7PHWxNXYacBQ0TfV1o9JAiG1GSGE6HMr3isiQ"},"resolveWithFullResponse":true,"simple":false,"strictSSL":true,"followAllRedirects":true,"method":"POST","path":"/auth/api.pococpauto.mcmp.local/login","headers":{},"uri":"https://vault.apps.pococpauto.mcmp.local/v1/auth/api.pococpauto.mcmp.local/login","transform2xxOnly":false},"stack":"RequestError: Error: self signed certificate in certificate chain\n    at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:310:20)\n    at Request.EventEmitter.emit (domain.js:482:12)\n    at Request.onRequestError (/app/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:310:20)\n    at ClientRequest.EventEmitter.emit (domain.js:482:12)\n    at TLSSocket.socketErrorListener (_http_client.js:426:9)","type":"Error","msg":"failure while polling the secret argocd/test-secret"}
```

(above jwt token is a dummy value because of security concerns)
Is there any way to disable the SSL verification here ? ( with  the same token after disabling SSL verification and using curl command, I could get result from vault )

**Comment by Flydiverny** [comment]
To bypass SSL verification for vault you should be able to set `VAULT_SKIP_VERIFY` to any value, according to what I can see in node-vault which is used to communicate with vault

https://github.com/kr1sp1n/node-vault/issues/27
https://github.com/kr1sp1n/node-vault/pull/45/files

**Comment by Flydiverny** [comment]
@tonythomasm A probably better alterantive is to provide the cert so its not rejected.

https://github.com/godaddy/kubernetes-external-secrets/pull/239/files
