### ISSUE TITLE
.kube/config missing after kubectl applying exerternal-secrets.yml

### ISSUE THREAD

**Issue by brunocous** [godaddy/kubernetes-external-secrets#72]
After kubectl applying the example deployment file `external-secrets.yml`, it keeps complaining about not being able to find the kubeconfig file (see log below from pod). 

I've seen that in commit #70 this file (that I'm still using) was removed. Is this way of deploying not supported anymore? Is there something else I could check? 
The proposed Helm chart is basically just a templated version of this deleted file, so I guess I will get the same type of error.

```
npm info it worked if it ends with ok
npm info using npm@6.4.1
npm info using node@v10.15.1
npm info lifecycle kubernetes-external-secrets@1.2.0~prestart: kubernetes-external-secrets@1.2.0
npm info lifecycle kubernetes-external-secrets@1.2.0~start: kubernetes-external-secrets@1.2.0
 > kubernetes-external-secrets@1.2.0 start /app
> ./bin/daemon.js
 fs.js:115
    throw err;
    ^
 Error: ENOENT: no such file or directory, open '/home/node/.kube/config'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at cfgPaths.map.cfgPath (/app/node_modules/kubernetes-client/lib/config.js:221:37)
    at Array.map (<anonymous>)
    at loadKubeconfig (/app/node_modules/kubernetes-client/lib/config.js:220:28)
    at Object.fromKubeconfig (/app/node_modules/kubernetes-client/lib/config.js:62:33)
    at Object.<anonymous> (/app/config/index.js:17:34)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm info lifecycle kubernetes-external-secrets@1.2.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@1.2.0 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kubernetes-external-secrets@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 523ms
 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-05-27T07_56_42_702Z-debug.log
```

edit: for completion sake, I converted the deleted file to terraform code using the kubernetes provider (see below), but still get the same error.
```terraform
resource "kubernetes_cluster_role_binding" "ext-secret-cluster-role-binding" {
  metadata {
    name = "kubernetes-external-secrets-cluster-role-binding"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind = "ClusterRole"
    name = "kubernetes-external-secrets-cluster-role"
  }
  subject {
    kind = "ServiceAccount"
    name = "kubernetes-external-secrets-service-account"
    namespace = "kubernetes-external-secrets"
  }
}

resource "kubernetes_cluster_role" "ext-secret-cluster-role" {
  metadata {
    name = "kubernetes-external-secrets-cluster-role"
  }

  rule {
    api_groups = [""]
    resources = ["secrets"]
    verbs = ["create", "update"]
  }
  rule {
    api_groups = ["apiextensions.k8s.io"]
    resources = ["customresourcedefinitions"]
    verbs = ["create"]
  }
  rule {
    api_groups = ["apiextensions.k8s.io"]
    resources = ["customresourcedefinitions"]
    resource_names = ["externalsecrets.kubernetes-client.io"]
    verbs = ["get", "update"]
  }
  rule {
    api_groups = ["kubernetes-client.io"]
    resources = ["externalsecrets"]
    verbs = ["get", "watch", "list"]
  }
}

resource "kubernetes_namespace" "ext-secret-namespace" {
  metadata {
    name = "kubernetes-external-secrets"
  }
}

resource "kubernetes_service_account" "ext-secret-service-account" {
  metadata {
    name = "kubernetes-external-secrets-service-account"
    namespace = "kubernetes-external-secrets"
  }
}

resource "kubernetes_deployment" "ext-secret-deployment" {
  "metadata" {
    labels {
      name = "kubernetes-external-secrets"
    }
    name = "kubernetes-external-secrets"
    namespace = "kubernetes-external-secrets"
  }
  "spec" {
    replicas = "1"
    selector {
      match_labels {
        name = "kubernetes-external-secrets"
      }
    }
    "template" {
      "metadata" {
        labels {
          name = "kubernetes-external-secrets"
          service = "kubernetes-external-secrets"
        }
      }
      "spec" {
        service_account_name = "kubernetes-external-secrets-service-account"
        container {
          name = "kubernetes-external-secrets"
          image_pull_policy = "Always"
          image = "godaddy/kubernetes-external-secrets:1.2.0"
        }
      }
    }
  }
}
```

**Comment by brunocous** [comment]
Closing issue. Deploying using helm chart solved the problem somehow.
